<!--<?xml version="1.0" encoding="utf-8"?>-->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>protobuf-net-fsharp</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <EnablePackageValidation>false</EnablePackageValidation>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <OutputPath>./bin</OutputPath>
	  <Version>9.0.14.300</Version>
	  <Configurations>Debug;Release;DbgWithNoDep</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <None Include="PostBuildEvent.ps1" />
    <Compile Include="MethodHelpers.fs" />
    <Compile Include="ZeroValues.fs" />
    <Compile Include="Surrogates.fs" />
    <Compile Include="CodeGen.fs" />
    <Compile Include="ProtobufUtils.fs" />
    <Content Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="3.2.45" />
    <PackageReference Include="protobuf-net.Core" Version="3.2.45" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="9.0.300" />
  </ItemGroup>
  <!--<Import Project="..\..\.paket\Paket.Restore.targets" />-->

	<PropertyGroup>
		<PackageId>FAkka.ProtoBuf.FSharp</PackageId>
	</PropertyGroup>

	<Target Name="PostPackNugetDeployWindows" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
		<Exec Command="powershell -c &quot;write-host '====== Start Post-Build Event ======'&quot;&#xD;&#xA;powershell .\PostBuildEvent.ps1 FAkka.ProtoBuf.FSharp" />
	</Target>
	
</Project>
